Map<String, dynamic> remoteConfigSettings = {
  'colorGray1': '0xff2B2932',
  'colorGray2': '0xff373440',
  'colorGray3': '0xff433F4E',
  'colorText': '0xffececee',
  'colorBlue': '0xff465166',
  'login_button_text': 'Sign In with Google',
  'balance': 'Balance',
  'shop': 'Shop',
  'earn': 'Earn',
  'support': 'Support',
  'settings': 'Settings',
  'clear_button': 'Clear',
  'save_button': 'Save',
  'steam_trade_url': 'Steam trade url',
  'logout': 'Logout',
  'd3': 'View 3d',
  'buy': 'Buy',
  'google_ads': 'Google Ads',
  'cash_out_waiting': 'Please wait...',
  'serverUrl': 'https://compensator.keenetic.pro:444/',
  'httpServerUrl': 'http://compensator.keenetic.pro:445/',
//   'serverUrl': 'http://192.168.1.100:5002',
//   'httpServerUrl': 'http://compensator.keenetic.pro:445/',
  'close_chat': 'Close',
};
